export enum StoreName{
    // LIMIT = 'Limit',
    // EXPENSE = 'Expense',
    // EXPENSES_ACTUAL = 'expenses_actual',
    // EXPENSES_PLAN = 'expenses_plan',
    // EXPENSES_ACTIONS = 'expensesActions',
    // TRAVEL = 'Travel',
    // TRAVEL_ACTIONS = 'travelActions',
    // CHECKLIST = 'Checklist',
    // TRAVEL_WAYPOINTS = 'travel_waypoints',
    // ROUTE = 'route',
    // CURRENCY = 'Currency',
    // Photo = 'Photo',
    // STORE_ACTIONS = 'storeActions',
    // USERS = 'User',
    // UPDATE = 'update',
    // HOTELS = 'Hotel',
    // ROAD = 'ROAD',
    // APPOINTMENTS = 'appointment',
    // ERRORS = 'errors',
    // UPDATED_TRAVEL_INFO = 'updatedTravelInfo',
    // ACTION = 'Action',
    // MESSAGE = 'Message',
    // PLACE = 'Place',
    // UNINITIALIZED = 'uninitialized'

    ITEMS = 'Items',
    STORE = 'Store',
    SECTIONS = 'Sections',

}